server:
  port: ${SERVER_PORT:8080}

spring:
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer